# Generated by Django 3.2.8 on 2022-02-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagittapro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='width',
            name='width',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='clss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sagittapro.class'),
            preserve_default=False,
        ),
    ]
