# Generated by Django 3.2.8 on 2022-02-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagittapro', '0002_auto_20220208_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clss',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
