# Generated by Django 3.2.8 on 2022-01-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagittapro', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
